# Generated by Django 4.0.6 on 2022-07-23 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_bookmark_like_reply_remove_feed_like_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='nickname',
            field=models.TextField(default=True),
        ),
    ]
